### PR TITLE
Update branding assets

### PR DESCRIPTION
**Pull request by vijayyadav06**
changing favicon and logo
image

### CODE REVIEW

**Comment by mycarrysun** [comment]
Just a comment on the logo itself - I can't really tell what the hand means. If I didn't know we were open columbus, I would immediately think either change.org or hand.org

**Comment by mollyhenderson** [comment]
I agree that `hand` `.org` is pretty confusing. Could we put the whole `columbushelper.org` logo there? Or maybe remove the `.org`, and just have the hand?

**Comment by mycarrysun** [comment]
> I agree that `hand` `.org` is pretty confusing. Could we put the whole `columbushelper.org` logo there? Or maybe remove the `.org`, and just have the hand?

Yea I think the `.org` is what throws it off, like you try to make it into a domain name in your head. I agree with @mollyhenderson here

**Comment by vijayyadav06** [comment]
thanks you both @mollyhenderson  and @mycarrysun, we updated the svg logo to have columbushelper in white to show up

image

**Pull request merged**
