### PR TITLE
bump to node 10 lts, fix clicking tel on mobile

### PR DESCRIPTION
**Pull request by mihiramin89**
- Bump to node 10.15.3 (latest lts for 10)
- When users click the phone number, it will prompt them if they would like to call that number

### CODE REVIEW

**Comment by mihiramin89** [comment]
Fixes issue #12

**Comment by delbertlegg** [comment]
When I click the link in the browser, it attempts to navigate like it's clicking a URL.

**Comment by mihiramin89** [comment]
> Phone number is currently being treated like a URL in browser. Will try to navigate and fail.

@delbertlegg interesting it seems to work for me in firefox & safari when i run it locally. What browser are you using and what OS? wonder if Apple is doing something to make it work.

**Comment by delbertlegg** [comment]
> > Phone number is currently being treated like a URL in browser. Will try to navigate and fail.
> 
> @delbertlegg interesting it seems to work for me in firefox & safari when i run it locally. What browser are you using and what OS? wonder if Apple is doing something to make it work.

I pulled it down and tested locally in Firefox, running Ubuntu 18.

**Comment by vijayyadav06** [comment]
whats the status of this PR? can we merge? its nice to have the number called when clicked.

**Comment by mihiramin89** [comment]
Since we are targeting tablets, I do not think the linux/firefox bug is as big of an issue right now. I think we can merge this. Thoughts @delbertlegg?

**Comment by delbertlegg** [comment]
Sorry, hectic day yesterday. I think we could probably log it as a bug and
move on?

**Comment by mihiramin89** [comment]
Merging. Created this issue: https://github.com/orgs/SCODEMeetup/projects/8#card-21997464

**Pull request merged**
